sonar.projectKey=mindgraph
sonar.projectName=Mindgraph
sonar.sourceEncoding=UTF-8

sonar.sources=desktop/src/main/kotlin
sonar.tests=desktop/src/test/kotlin

sonar.exclusions=**/build/**,**/.gradle/**,**/.kotlin/**
